## The default degree of task parallelism
parallelism.default: 1
classloader.resolve-order: parent-first

## Flink Historical task retention time of the cluster
web.history: 200
jobstore.expiration-time: 259200
web.submit.enable: false

## Flink Checkpoint Congfig. By default, local storage is used. 
## If you have the ability and need to deploy the operator cluster on multiple servers and have distributed storage, such as HDFS, S3, and Minio, you can change the storage path to distributed storage
state.checkpoint-storage: filesystem
state.checkpoints.dir: file:///opt/flink/checkpoint
state.savepoints.dir: file:///opt/flink/savepoint

##Specifies the Flink cluster monitoring indicator exposure mode
metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
taskmanager.network.detailed-metrics: true

##Support OSS as storage configuration. OSS is used as the data storage medium by default in the test network
fs.oss.endpoint: network-testnet.chainbasehq.com
##fs.oss.credentials.provider: com.aliyun.oss.common.auth.EnvironmentVariableCredentialsProvider
fs.oss.accessKeyId: xxxxxx
fs.oss.accessKeySecret: xxxxxx

## Minimum memory configuration for the Flink Jobmanager and Taskmanager JVM. For normal usage, leave this as the default.
env.java.opts.taskmanager: -Xms512m
env.java.opts.jobmanager: -Xms512m

## Maximum memory configuration for the Flink Jobmanager and Taskmanager JVM. Generally, the value is set to 80% of the server memory.
## Warning！！If the setting is too high, the OOM may appear.
taskmanager.memory.process.size: 2g
taskmanager.memory.jvm-metaspace.size: 256mb
jobmanager.memory.process.size: 2g
jobmanager.memory.enable-jvm-direct-memory-limit: true
## The number of tasks that the current operator can run in parallel.
## This configuration item is related to the "taskmanager.Memory.Process.size" configuration.
## general calculation for the "taskmanager.numberOfTaskSlots" * 512 MB = "taskmanager.memory.process.size"
## If you have more tuning knowledge, you can reduce or increase this configuration as appropriate.
taskmanager.numberOfTaskSlots: 4


## Flink Cluster RPC configuration
web.refresh-interval: 30000
jobmanager.io-pool.size: 500
blob.fetch.num-concurrent: 200
jobmanager.future-pool.size: 100
rest.client.max-content-length: 1048576000
taskmanager.network.request-backoff.max: 40000
resourcemanager.taskmanager-timeout: 30000

io.tmp.dirs: /opt/flink/tmp
env.log.dir: /opt/flink/log
pekko.ask.timeout: 120s
rest.bind-port: 8081
blob.server.port: 6124
jobmanager.rpc.port: 6123
query.server.port: 6125
jobmanager.rpc.address: localhost