api:
  base_url: "https://api.chainbase.com"
  endpoints:
    chains: "/api/v1/metadata/network_chains"

app:
  network: "TestNet"
  version: "v1.1.1"

node:
  job_manager_image_arm64: "repository.chainbase.com/manuscript-node/manuscript-node:latest"
  hasura_image_arm64: "repository.chainbase.com/manuscript-node/graphql-engine-arm64:latest"
  job_manager_image_amd64: "repository.chainbase.com/manuscript-node/manuscript-node:latest"
  hasura_image_amd64: "repository.chainbase.com/manuscript-node/graphql-engine-amd64:latest"
